title: BleedTV Podcast
email: bleedtvpodcast@gmail.com
description: >-
  BleedTV is a podcast for the fans of great movies & television such as The Walking Dead, Game of Thrones, Fear The Walking Dead, True Detective, Preacher and more.
url: "https://bleedtv.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bleedtvpodcast
github_username:  bleedtv
locale: en-US
twitter:
  username: "bleedtvpodcast"
# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll

paginate: 3
paginate_path: /page:num/

repository: bleedtv/bleedtv.github.io
minimal_mistakes_skin: neon
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: false

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bleedtvpodcast"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .ruby-gemset
  - .ruby-version
  - README.md
